name: Python application

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest fastapi httpx
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    - name: Test with pytest
      run: |
        cd backend
        pytest
